travis:
  secure:
    BINSTAR_TOKEN: i/y2hxzjbvIf1V8wvRhEZlefUUT/LOTqMLGGpps7eV0BemlChwQ/A45jry7MjC3y4huUjBIKCSVM2HFx49Vea8GGREpgJVOWkrxKvNxdY6iUwsI/Pht/SsqKJgebsrK2UfaDxl0udzsD9wEzkAkCMx3dzLvkkmfINilUcOH4mwJv2psEANC1V4RJ/hbYoArPiWrwtoqNJ/GIb7hOZQNqdBJgw5Uj3KMXI3ft1LwpWdmT4OW4dMEyvIg912mtYth/vR2pZGmJyM/008bRVyWY1DE57YKE0irKCInGB+oWDgQXpxZmII5OvoCdskzQrSX6mHV/iuEJSa7sfBW0XJRZXChtLp8rwppCpPOKxe+hKt90vaUOfqHN7c+HLRAjAEy+LAAUukwPeFx3sSeIwuTn3xtl/R6hOCT+lDZ+YScAiHxCItdRPvMD+VBcMVJWJhMpxrMExOQhiPiECBxUmuwe8wo+VeFYMMXea60rFUU4JzD0pX/C47Rse42vCjGpiHkdkCpMsWjJY1juFnq4W5IDxNVaJK0guBaFv8ldkU/iy1i9Ht2Wwcom1pQq/mVyAwyxaWgnqAZxWE6Hi+FEVKarID6IoFHNJsQ6dgo8hVzg48qtV1IRiRrSkBk0NYz1pQoHyfDRGn3xS016Z0whooITrwSHNk/VQC5fygGZVRou5Ns=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
