travis:
  secure:
    BINSTAR_TOKEN: jRJbC5YRyf8u+U8BdjUrDZrZ4IkbAmOulklZRhq/zoiJDQkDXQsBjK+zi8hSPkynZBK1gEvYIUprx086rpt9qqbDtKEmjzlNrO3Z6rSoOuUbaJrUWJ3rNNqfx59n7n28U317f9PgCSl2PI4cLxdwXBkbovdjGqAgaF39kG3M0N6FnyF9ei8HFSlvTonM2aviWrIk2jVHL2nuxDFj1+eIiHj4qKR4UWf+A8K4tyesRy7zUANHMxDwcX+cAkv6QE8eBCVnRHe+h3re6hhAnRez3ZKRLyDUr3H+hsVu/k32bZOECgtoesNJM+fLqoLycX3rhn5pTHBIladA4xWbOKuARVgv6riUCMsziULjxMebSQ1PL3OZQObv1U1EYTeLi29vxT0SR8Lvs9XA2VsOLjKl8LtTmKajRg0yZitm9ymatsws74zfsP1JIBv3D42zaNWB2sIWVmC6TUVHg+bvmoa5CFA9S8P1KBMLWsCJz+tATEZNpumKT03j0PKuuZLScmqkqQwg7UmcWxfpcWx9VSQz5Fr40gCI0k6Nnm5Evf+5vDe0w3HmV56GCo711WqCAjqlnZ8/t1CHbwVZ0WPW/eftbYi1rivdU5oB1H3NzgJwUukbB4qYtPcRZ90Vx2+/QPDcV4vGrmENXQNRnX4vlH3XODEzdPHKH9gd0OkQvLcZBrw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
